# Generated by Django 3.2.11 on 2022-01-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
