# Generated by Django 3.2.10 on 2022-01-09 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
