# Generated by Django 3.2.10 on 2022-01-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_system', '0002_project_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(),
        ),
    ]
