# Generated by Django 3.2.11 on 2022-01-17 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_system', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 9-15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
