# Generated by Django 3.2.11 on 2022-01-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_system', '0004_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectownership',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management_system.project'),
        ),
    ]
