# Generated by Django 3.2.10 on 2022-01-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_system', '0005_alter_comments_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management_system.project'),
        ),
    ]
