# Generated by Django 3.2.11 on 2022-01-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_system', '0006_alter_comments_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_name', to='project_management_system.profile'),
        ),
    ]
